publishDir = "docs"
baseURL = "https://www.mumazhe.net/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "牧码者"
# Main Menu
[[menu.main]]
name = "首页"
url = "#home"
weight = 1
[[menu.main]]
name = "关于我们"
url = "#about"
weight = 2
[[menu.main]]
name = "服务范围"
url = "#service"
weight = 3
[[menu.main]]
name = "作品展示"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "发展经历"
url = "#resume"
weight = 5
[[menu.main]]
name = "最新动态"
url = "#blog"
weight = 6
[[menu.main]]
name = "联系我们"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "关于我们"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Mumazhe 2021"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "陕西省西咸新区沣东新城世纪大道中段南侧西咸人才大厦七层C2-210"
email = "public1@mail.mumazhe.net"
openingHours = "周一到周五，9：00-18：00。"
phone = "+86 178 1030 1001"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
